name: SpellCheckAll

on:
  pull_request:
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: streetsidesoftware/cspell-action@v2
        with:
          config: https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/cspell/.cspell.json
          files: "**"
          incremental_files_only: false
          strict: true
